# Variables to be configured only on spine switches

# VXLAN related features to be enabled on spine switches

vxlan_features:
  - feature: ospf
    state: enabled
  - feature : bgp
    state: enabled
  - feature: pim
    state: enabled
  - feature: nv overlay
    state: enabled

# Leaf facing interfaces to be configured as "unnumbered"

leaf_facing_ifaces:
  - name: Ethernet1/1
  - name: Ethernet1/2
  - name: Ethernet1/3

# Loopback interface to be used for various tasks

loopback_ifaces:
  - name: Loopback0
  - name: Loopback1

# Variables to be used within the Play

spine1_loopback0: 1.1.0.191
spine2_loopback0: 1.1.0.192

# Anycast RP Address to be configured on Spines

anycast_rp_address: 1.1.1.190

# BGP Configuration variables

bgp_leaf_neighbors:
  - neighbor: '1.1.0.91'
  - neighbor: '1.1.0.92'
  - neighbor: '1.1.0.93'

